### ISSUE TITLE
Could not find MaxEntIRL in the baselines

### ISSUE THREAD

**Issue by RTRodoshi** [twni2016/f-IRL#3]
First of all, Thank you for making this repository publicly available.
I am trying to reproduce some of the results, however, I couldn't find the MaxEntIRL implementation in the baselines. I am not sure whether I am missing something here. Can you please clarify?
Thanks in advance.

**Comment by twni2016** [comment]
Hi, MaxEntIRL is implemented in `firl` folder using obj `maxentirl`, not in the `baselines` folder. Please also see the experiments section in the readme for commands.
